title: Practicing git
author: amkeare
email: noup@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Learning more about git

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
